name: fsm_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  logger: ^2.5.0
  hydrated_bloc: ^9.1.5
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  flutter_svg: ^2.0.16
  path_provider: ^2.1.5
  shared_preferences: ^2.3.3
  get_it: ^8.0.2
  connectivity_plus: ^4.0.0
  google_fonts: ^6.2.1
  device_info_plus: ^11.1.1
  dio: ^5.7.0
  iconsax: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  assets:
     - assets/images/
     - assets/fonts/
     - assets/vectors/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

